- name: C++ Style Check
  # You may pin to the exact commit or the version.
  # uses: coleaeason/actions-uncrustify@70f17f40b57ff933121e3cccafde98ea3eb0dee9
  uses: coleaeason/actions-uncrustify@v1
  with:
    # Alternate configuration file to use
    configPath: # optional
